# Generated by Django 4.2 on 2023-05-24 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_exchangerateprovider_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
